name: AcidRain
main: com.escapeNT.acidRain.AcidRain
version: 1.2.6
author: escape
commands:
  Acidrain:
    description: Starts acid rain in the current or specified world.
    usage: |
      /<command> (world) (time)